let a = 0
let c = ""


try {
    console.log(a + b + c)
} catch (err) {
    console.log(err)
}